### ISSUE TITLE
Type 'any[]' is not assignable to type '[...SchemaParameters<S>]'.  (TypeScript 4.3 / Deno 1.11)

### ISSUE THREAD

**Issue by bradenmacdonald** [neuledge/computed-types#119]
I'm getting an error when trying to import this library with the latest version of Deno:

```
import Schema, { Type, string, number, array } from "https://denoporter.sirjosh.workers.dev/v1/deno.land/x/computed_types@v1.6.0/src/index.ts";
```

gives:

```
error: TS2345 [ERROR]: Argument of type 'any[] | [string] | [S] | [S] | [{ [K in keyof S]: SchemaParameters<S[K]>[0]; }] | [{ [K in keyof SchemaKeysObject<S>]: SchemaParameters<S[K]>[0]; }]' is not assignable to parameter of type '[...SchemaParameters<S>]'.
  Type 'any[]' is not assignable to type '[...SchemaParameters<S>]'.
    Target requires 1 element(s) but source may have fewer.
                throw createValidationError(errors, mainError || error, ...args);
                                                                        ~~~~~~~
    at https://denoporter.sirjosh.workers.dev/v1/deno.land/x/computed_types@v1.6.0/src/schema/compiler.ts:108:73

TS2345 [ERROR]: Argument of type 'any[] | [string] | [S] | [S] | [{ [K in keyof S]: SchemaParameters<S[K]>[0]; }] | [{ [K in keyof SchemaKeysObject<S>]: SchemaParameters<S[K]>[0]; }]' is not assignable to parameter of type '[...SchemaParameters<S>]'.
                throw createValidationError(errors, mainError || error, ...args);
                                                                        ~~~~~~~
    at https://denoporter.sirjosh.workers.dev/v1/deno.land/x/computed_types@v1.6.0/src/schema/compiler.ts:114:73

Found 2 errors.
```

Using:
```
deno --version
deno 1.11.1 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

**Comment by moshest** [comment]
Please try `v1.8.0`

Thanks for reporting!

**Comment by bradenmacdonald** [comment]
It works! Thanks for the quick fix, @moshest :)
